{% set name = "rootstock" %}
{% set version = "0.7.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rootstock-{{ version }}.tar.gz
  sha256: d928fe62bc305b00b9606f925c5a4025fd1cd9983e31ce9d687e3d1c7115f226

build:
  noarch: python
  entry_points:
    - rootstock = rootstock.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - ase >=3.22
    - numpy >=1.24
    - packaging >=21.0

test:
  imports:
    - rootstock
  commands:
    - pip check
    - rootstock --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/rootstock/
  summary: MLIP calculators with isolated Python environments
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
